### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by marcustisater** [postcss/brand#1]
Do we need to add any license for usage of media from this repository or what includes as "standard" in these cases. I figured if anyone would want to share/use anything.

**Comment by stephenway** [comment]
Depends, does @ai have a copyright or some claim to the PostCSS title? logo?

**Comment by marcustisater** [comment]
Yeah, just a suggestion, maybe it dosen't need to be added? I don't know too much about these things I'm afraid.

**Comment by ai** [comment]
PostCSS logo was published under MIT.

But I thnk CC-BY is better, for art because license text is more oriented to art, not just for code, like MIT.
http://opendata.stackexchange.com/questions/245/cc-by-vs-mit-or-bsd-licenses-regarding-re-use

As I understand MIT and CC-BY compatible. Anyway we can relicense this art work for any license :)

**Comment by stephenway** [comment]
Yea so we can separate the repo by folder (logo and artwork), and just drop the right license into each one instead of just one LICENSE file in the top level.

**Comment by ai** [comment]
OK, I will do it tomorrow because I am too drunk right now and CC site has no plain text license file :).

**Comment by ai** [comment]
Done aae43797d8ae282e4fbdc2b3eb45352c041c4a26

**Comment by marcustisater** [comment]
:joy: 

> OK, I will do it tomorrow because I am too drunk right now and CC site has no plain text license file :)
